version: '3'
services:
  bckend:
    build:
      context: backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    working_dir: /app/src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
